// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"time"

	"github.com/google/uuid"
)

type DisputeDB struct {
	ID              uuid.UUID `db:"id" json:"id"`
	Title           string    `db:"title" json:"title"`
	Description     string    `db:"description" json:"description"`
	CreatedAt       time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt       time.Time `db:"updated_at" json:"updatedAt"`
	Cryptocurrency  string    `db:"cryptocurrency" json:"cryptocurrency"`
	Amount          int       `db:"amount" json:"amount"`
	ImageData       []byte    `db:"image_data" json:"imageData"`
	ImageType       *string   `db:"image_type" json:"imageType"`
	ContractAddress string    `db:"contract_address" json:"contractAddress"`
	EndsAt          time.Time `db:"ends_at" json:"endsAt"`
	NextDeadline    time.Time `db:"next_deadline" json:"nextDeadline"`
}

type Evidence struct {
	ID          uuid.UUID `db:"id" json:"id"`
	DisputeID   uuid.UUID `db:"dispute_id" json:"disputeID"`
	UserID      uuid.UUID `db:"user_id" json:"userID"`
	Description string    `db:"description" json:"description"`
	ImageData   []byte    `db:"image_data" json:"imageData"`
	ImageType   *string   `db:"image_type" json:"imageType"`
	CreatedAt   time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt   time.Time `db:"updated_at" json:"updatedAt"`
}

type InvestigationDB struct {
	ID        uuid.UUID           `db:"id" json:"id"`
	DisputeID uuid.UUID           `db:"dispute_id" json:"disputeID"`
	Total     int                 `db:"total" json:"total"`
	P1        int                 `db:"p1" json:"p1"`
	P2        int                 `db:"p2" json:"p2"`
	Draw      int                 `db:"draw" json:"draw"`
	Status    InvestigationStatus `db:"status" json:"status"`
	CreatedAt time.Time           `db:"created_at" json:"createdAt"`
	EndsAt    time.Time           `db:"ends_at" json:"endsAt"`
	Title     string              `db:"title" json:"title"`
}

type User struct {
	ID                   uuid.UUID `db:"id" json:"id"`
	Username             string    `db:"username" json:"username"`
	ChatID               int64     `db:"chat_id" json:"chatID"`
	CreatedAt            time.Time `db:"created_at" json:"createdAt"`
	NotificationEnabled  bool      `db:"notification_enabled" json:"notificationEnabled"`
	DisputeReadiness     bool      `db:"dispute_readiness" json:"disputeReadiness"`
	MinimumDisputeAmount int       `db:"minimum_dispute_amount" json:"minimumDisputeAmount"`
	Rating               int       `db:"rating" json:"rating"`
}

type User2Dispute struct {
	ID        uuid.UUID `db:"id" json:"id"`
	UserID    uuid.UUID `db:"user_id" json:"userID"`
	DisputeID uuid.UUID `db:"dispute_id" json:"disputeID"`
	Vote      bool      `db:"vote" json:"vote"`
	Result    Result    `db:"result" json:"result"`
	Status    Status    `db:"status" json:"status"`
	Claim     bool      `db:"claim" json:"claim"`
}

type User2Investigation struct {
	ID              uuid.UUID           `db:"id" json:"id"`
	UserID          uuid.UUID           `db:"user_id" json:"userID"`
	InvestigationID uuid.UUID           `db:"investigation_id" json:"investigationID"`
	Vote            string              `db:"vote" json:"vote"`
	Result          InvestigationResult `db:"result" json:"result"`
}
