// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"time"

	"github.com/google/uuid"
)

type Dispute struct {
	ID              uuid.UUID `db:"id" json:"id"`
	Title           string    `db:"title" json:"title"`
	Description     string    `db:"description" json:"description"`
	CreatedAt       time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt       time.Time `db:"updated_at" json:"updatedAt"`
	Cryptocurrency  string    `db:"cryptocurrency" json:"cryptocurrency"`
	ImageData       []byte    `db:"image_data" json:"imageData"`
	ImageType       *string   `db:"image_type" json:"imageType"`
	ContractAddress string    `db:"contract_address" json:"contractAddress"`
	EndsAt          time.Time `db:"ends_at" json:"endsAt"`
	NextDeadline    time.Time `db:"next_deadline" json:"nextDeadline"`
	AmountNano      int64     `db:"amount_nano" json:"amountNano"`
}

type Evidence struct {
	ID            uuid.UUID `db:"id" json:"id"`
	Description   string    `db:"description" json:"description"`
	ImageData     []byte    `db:"image_data" json:"imageData"`
	ImageType     *string   `db:"image_type" json:"imageType"`
	CreatedAt     time.Time `db:"created_at" json:"createdAt"`
	ParticipantID uuid.UUID `db:"participant_id" json:"participantID"`
}

type Investigation struct {
	ID        uuid.UUID           `db:"id" json:"id"`
	DisputeID uuid.UUID           `db:"dispute_id" json:"disputeID"`
	Total     int                 `db:"total" json:"total"`
	P1        int                 `db:"p1" json:"p1"`
	P2        int                 `db:"p2" json:"p2"`
	Draw      int                 `db:"draw" json:"draw"`
	Status    InvestigationStatus `db:"status" json:"status"`
	CreatedAt time.Time           `db:"created_at" json:"createdAt"`
	EndsAt    time.Time           `db:"ends_at" json:"endsAt"`
	Title     string              `db:"title" json:"title"`
}

type Juror struct {
	ID              uuid.UUID           `db:"id" json:"id"`
	UserID          uuid.UUID           `db:"user_id" json:"userID"`
	InvestigationID uuid.UUID           `db:"investigation_id" json:"investigationID"`
	Vote            string              `db:"vote" json:"vote"`
	Result          InvestigationResult `db:"result" json:"result"`
}

type Participant struct {
	ID        uuid.UUID `db:"id" json:"id"`
	UserID    uuid.UUID `db:"user_id" json:"userID"`
	DisputeID uuid.UUID `db:"dispute_id" json:"disputeID"`
	Vote      bool      `db:"vote" json:"vote"`
	Result    Result    `db:"result" json:"result"`
	Status    Status    `db:"status" json:"status"`
	Claim     bool      `db:"claim" json:"claim"`
}

type User struct {
	ID                       uuid.UUID `db:"id" json:"id"`
	Username                 string    `db:"username" json:"username"`
	ChatID                   int64     `db:"chat_id" json:"chatID"`
	CreatedAt                time.Time `db:"created_at" json:"createdAt"`
	NotificationEnabled      bool      `db:"notification_enabled" json:"notificationEnabled"`
	DisputeReadiness         bool      `db:"dispute_readiness" json:"disputeReadiness"`
	Rating                   int       `db:"rating" json:"rating"`
	PhotoUrl                 *string   `db:"photo_url" json:"photoUrl"`
	MinimumDisputeAmountNano int64     `db:"minimum_dispute_amount_nano" json:"minimumDisputeAmountNano"`
	InvestigationReadiness   bool      `db:"investigation_readiness" json:"investigationReadiness"`
}
